import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/ui/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import { Dialog, DialogContent, DialogTitle } from '@radix-ui/react-dialog';
import { VisuallyHidden } from '@radix-ui/react-visually-hidden';

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"], 
  variable: '--font-jetbrainsMono' 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}

// Example dialog structure
function ExampleDialog() {
  return (
    <Dialog>
      <DialogContent>
        <DialogTitle>
          <VisuallyHidden>Dialog Title</VisuallyHidden>
        </DialogTitle>
        {/* ...existing dialog content... */}
      </DialogContent>
    </Dialog>
  );
}
